name: identitysamplesb2c-videocalling

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-deploy-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build --no-cache --build-arg app_version=1.0.$GITHUB_RUN_NUMBER --build-arg source_version=$GITHUB_SHA -t jelledruyts/identitysamplesb2c-videocalling:latest -f ./Calling/Dockerfile ./Calling
    - name: Push Docker Image to Registry
      run: docker push jelledruyts/identitysamplesb2c-videocalling:latest